add routine

diff --git a/.github/workflows/android_build_test_01.yml b/.github/workflows/android_build_test_01.yml
--- a/.github/workflows/android_build_test_01.yml
+++ b/.github/workflows/android_build_test_01.yml
@@ -15,6 +15,23 @@ jobs:
 
       - uses: actions/checkout@v2
 
+      - name: Check PR title
+        if: ${{ github.event.issue.pull_request }}
+        env:
+          TITLE: ${{ github.event.pull_request.title }}
+        run: |
+          if [[ "$TITLE" =~ ^swit- ]]; then
+          echo "PR title valid"
+          else
+            echo "PR title invalid"
+            exit 1
+            fi
+
+      - name: Get PR Issue Number
+        if: ${{ github.event.issue.pull_request }}
+        run: |
+          echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
+
       - name: Set Up JDK
         uses: actions/setup-java@v3
         with:
@@ -63,13 +80,14 @@ jobs:
         id: unit_test
         run: ./gradlew test
 
+      # 테스트니까 메인 브랜치로
       - name: Build debug APK
         id: build_debug_apk
-        run: bash ./gradlew assembleDebug --stacktrace
+        if: ${{ github.ref == 'refs/heads/main' }}
+        run: ./gradlew assembleDebug
 
       # AppTester 배포 루틴 추가 필요
       # app/build/outputs/apk/dev/debug/app-dev-debug.apk
-
 
       # REPORT
 
